import type { Locale } from "@/lib/locale";

export const UI = {
  ko: {
    brand: "메이플 재획 정산",
    navAria: "주요 메뉴",
    secondaryAria: "보조 메뉴",
    navCalculator: "재획 정산기",
    navGuides: "가이드",
    navShowcase: "자랑 게시판",
    navTips: "유저 팁",
    navFeedback: "피드백",
    langSwitchLabel: "English",
    langSwitchAria: "Switch to English",
    footerLegalAria: "법적 고지",
    footerPrivacy: "개인정보처리방침",
    footerTerms: "이용약관",
    footerCopyright: (year: number, updated: string) =>
      `© ${year} wopsgame · 비공식 팬 도구 · 법적 문서 최종 개정: ${updated}`,
    guideIndexTitle: "재획 가이드",
    guideIndexBlurb: "제목을 누르면 본문으로 이동합니다. 페이지당 10개씩 표시됩니다.",
    guideBackHome: "← 재획 정산기로 돌아가기",
    guideBackList: "← 가이드 목록",
    guideListCta: "목록으로 가기",
    viewsBest: "조회수 BEST",
    recommendsBest: "추천 BEST",
    allGuides: "전체 가이드",
    statsLoading: "추천·조회수 불러오는 중…",
    statsCell: (rec: string, views: string) => `추천 ${rec} · 조회 ${views}`,
    prev: "이전",
    next: "다음",
    relatedTitle: "연관 가이드",
    relatedAll: "가이드 목록으로 →",
    recommendDone: (n: string) => `추천 완료 · ${n}`,
    recommendCta: (n: string) => `추천하기 · ${n}`,
    recommendAlready: "이미 추천한 글입니다.",
    recommendThanks: "추천해 주셔서 감사합니다!",
    recommendFail: "추천 처리에 실패했습니다. 잠시 후 다시 시도해 주세요.",
    calcTitle: "메이플 재획 정산",
    calcSubtitle: "2시간 사냥 시급 · 누적 정산",
    calcResetAll: "전체 초기화",
    calcResetConfirm: "오늘의 모든 기록과 타이머를 초기화할까요?",
    calcMoreGuides: "최신 가이드 더보기 →",
    emptyGuides: "등록된 가이드가 없습니다.",
    slotLabel: (n: 1 | 2 | 3) => `${n}회차`,
    slotSelectLabel: "재획 회차",
    formGround: "사냥터",
    formGroundGemGroup: "260 미만 · 코어 젬스톤",
    formGroundFragmentGroup: "260 이상 · 솔 에르다 조각",
    formMesoModeLabel: "메소 입력",
    formMesoModeNet: "순수 획득",
    formMesoModeRange: "시작/종료",
    formMesoNet: "순수 획득 메소",
    formMesoBefore: "시작 메소",
    formMesoAfter: "종료 메소",
    formExpNet: "순수 획득 EXP %",
    formFragment: "솔 에르다",
    formGem: "코어 젬",
    formAddOne: "+1",
    formAddFive: "+5",
    formRecordCta: "정산 결과 확인",
    timerTitle: "2시간 재획 타이머",
    timerTarget: "목표",
    timerCountUp: "카운트 업",
    timerCountDown: "카운트 다운",
    timerStart: "시작",
    timerStop: "정지",
    timerReset: "리셋",
    timerOverlay: "오버레이 모드",
    timerCloseOverlay: "닫기",
    exportSaveResult: "[정산 결과 이미지로 저장 (인증샷)]",
    exportBusy: "이미지 생성 중…",
    exportInlineBusy: "생성 중…",
    exportInlineIdle: "인증샷 저장",
    exportFilename: "메이플_재획_총정산.png",
    historyTitle: "사냥 히스토리",
    historyEmpty: "기록 없음",
    historyClearSlot: "회차 초기화",
    historyClearConfirm: (n: 1 | 2 | 3) =>
      `${n}회차 기록을 모두 삭제할까요?`,
    historyEntry: (n: number) => `기록 ${n}`,
    historyMesosSubtotal: "획득 메소 소계",
    historyRevenueSubtotal: "총수익 소계",
    historyMesos: "획득 메소",
    historyRevenue: "1회 총수익",
    historyExp: (v: string) => `순수 EXP ${v}`,
    presetOpen: "내 세팅 관리",
    presetTitle: "내 세팅 관리",
    presetServerLabel: "서버 선택",
    presetKms: "KMS (본서버)",
    presetHeroic: "GMS Heroic (리부트)",
    presetFragmentPrice: "에르다 조각 시세",
    presetGemPrice: "코어 젬스톤/기타 시세",
    presetHeroicHint: "GMS Heroic 서버는 경매장이 없어 순수 메소만 정산됩니다.",
    presetGround: "기본 주력 사냥터",
    presetSave: "세팅 저장",
    presetReset: "세팅만 초기화",
    presetSavedToast: "세팅이 저장되었습니다. 다음 방문 시에도 유지됩니다.",
    presetResetToast: "세팅이 기본값으로 초기화되었습니다. (사냥 기록은 유지됩니다)",
    presetClose: "닫기",
    presetBadgeKms: (fragment: string, gem: string) =>
      `KMS · 조각 ${fragment} / 젬 ${gem}`,
    presetBadgeHeroic: "GMS Heroic · 순수 메소",
    dashboardToday: "오늘의 총합",
  },
  en: {
    brand: "Maple Meso Calculator",
    navAria: "Primary",
    secondaryAria: "Secondary",
    navCalculator: "Meso Calculator",
    navGuides: "Guides",
    navShowcase: "Showcase",
    navTips: "Tips",
    navFeedback: "Feedback",
    langSwitchLabel: "한국어",
    langSwitchAria: "한국어로 전환",
    footerLegalAria: "Legal",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Use",
    footerCopyright: (year: number, updated: string) =>
      `© ${year} wopsgame · Unofficial fan tool · Legal docs last updated: ${updated}`,
    guideIndexTitle: "Hunting & Meso Guides",
    guideIndexBlurb: "Tap a title to open the full guide. 10 guides per page.",
    guideBackHome: "← Back to Meso Calculator",
    guideBackList: "← All guides",
    guideListCta: "Back to guide list",
    viewsBest: "Most viewed",
    recommendsBest: "Most recommended",
    allGuides: "All guides",
    statsLoading: "Loading views & recommends…",
    statsCell: (rec: string, views: string) => `${rec} recommends · ${views} views`,
    prev: "Prev",
    next: "Next",
    relatedTitle: "Related guides",
    relatedAll: "All guides →",
    recommendDone: (n: string) => `Recommended · ${n}`,
    recommendCta: (n: string) => `Recommend · ${n}`,
    recommendAlready: "You already recommended this guide.",
    recommendThanks: "Thanks for the recommendation!",
    recommendFail: "Could not save recommendation. Please try again.",
    calcTitle: "Maple Meso Calculator",
    calcSubtitle: "2-hour hunt wage · running settlement",
    calcResetAll: "Reset all",
    calcResetConfirm: "Clear today’s records and timer?",
    calcMoreGuides: "Browse English guides →",
    emptyGuides: "No English guides yet. Check back soon.",
    slotLabel: (n: 1 | 2 | 3) => `Session ${n}`,
    slotSelectLabel: "Session",
    formGround: "Map",
    formGroundGemGroup: "Below 260 · Nodestone",
    formGroundFragmentGroup: "260+ · Erda Fragment",
    formMesoModeLabel: "Meso input",
    formMesoModeNet: "Net gained",
    formMesoModeRange: "Start / End",
    formMesoNet: "Net mesos gained",
    formMesoBefore: "Start mesos",
    formMesoAfter: "End mesos",
    formExpNet: "Net EXP % gained",
    formFragment: "Erda Frag",
    formGem: "Nodestone",
    formAddOne: "+1",
    formAddFive: "+5",
    formRecordCta: "Confirm settlement",
    timerTitle: "2-Hour Hunt Timer",
    timerTarget: "Target",
    timerCountUp: "Count Up",
    timerCountDown: "Count Down",
    timerStart: "Start",
    timerStop: "Stop",
    timerReset: "Reset",
    timerOverlay: "Overlay mode",
    timerCloseOverlay: "Close",
    exportSaveResult: "[Save Result Image]",
    exportBusy: "Generating image…",
    exportInlineBusy: "Saving…",
    exportInlineIdle: "Save shot",
    exportFilename: "maple_hunt_settlement.png",
    historyTitle: "Hunt history",
    historyEmpty: "No records",
    historyClearSlot: "Clear session",
    historyClearConfirm: (n: 1 | 2 | 3) =>
      `Delete all records in Session ${n}?`,
    historyEntry: (n: number) => `Entry ${n}`,
    historyMesosSubtotal: "Meso subtotal",
    historyRevenueSubtotal: "Revenue subtotal",
    historyMesos: "Mesos gained",
    historyRevenue: "Session revenue",
    historyExp: (v: string) => `Net EXP ${v}`,
    presetOpen: "Preset Settings",
    presetTitle: "Preset Settings",
    presetServerLabel: "Server",
    presetKms: "GMS Interactive",
    presetHeroic: "GMS Heroic",
    presetFragmentPrice: "Erda Fragment price",
    presetGemPrice: "Nodestone / other price",
    presetHeroicHint:
      "GMS Heroic server relies only on pure mesos (Marketplace prices set to 0).",
    presetGround: "Default hunting map",
    presetSave: "Save Preset",
    presetReset: "Reset Preset",
    presetSavedToast: "Preset saved. It will load on your next visit.",
    presetResetToast: "Preset reset to defaults. (Hunt history kept)",
    presetClose: "Close",
    presetBadgeKms: (fragment: string, gem: string) =>
      `Interactive · Frag ${fragment} / Gem ${gem}`,
    presetBadgeHeroic: "GMS Heroic · Pure Meso Mode",
    dashboardToday: "Today’s totals",
  },
} as const;

export function ui(locale: Locale) {
  return UI[locale];
}
