import type { Locale } from "@/lib/locale";

export const UI = {
  ko: {
    brand: "메이플 재획 정산",
    navAria: "주요 메뉴",
    secondaryAria: "보조 메뉴",
    navCalculator: "재획 정산기",
    navGuides: "가이드",
    navShowcase: "자랑 게시판",
    navTips: "유저 팁",
    navFeedback: "피드백",
    langSwitchLabel: "English",
    langSwitchAria: "Switch to English",
    footerLegalAria: "법적 고지",
    footerPrivacy: "개인정보처리방침",
    footerTerms: "이용약관",
    footerCopyright: (year: number, updated: string) =>
      `© ${year} wopsgame · 비공식 팬 도구 · 법적 문서 최종 개정: ${updated}`,
    guideIndexTitle: "재획 가이드",
    guideIndexBlurb: "제목을 누르면 본문으로 이동합니다. 페이지당 10개씩 표시됩니다.",
    guideBackHome: "← 재획 정산기로 돌아가기",
    guideBackList: "← 가이드 목록",
    guideListCta: "목록으로 가기",
    viewsBest: "조회수 BEST",
    recommendsBest: "추천 BEST",
    allGuides: "전체 가이드",
    statsLoading: "추천·조회수 불러오는 중…",
    statsCell: (rec: string, views: string) => `추천 ${rec} · 조회 ${views}`,
    prev: "이전",
    next: "다음",
    relatedTitle: "연관 가이드",
    relatedAll: "가이드 목록으로 →",
    recommendDone: (n: string) => `추천 완료 · ${n}`,
    recommendCta: (n: string) => `추천하기 · ${n}`,
    recommendAlready: "이미 추천한 글입니다.",
    recommendThanks: "추천해 주셔서 감사합니다!",
    recommendFail: "추천 처리에 실패했습니다. 잠시 후 다시 시도해 주세요.",
    calcTitle: "메이플 재획 정산",
    calcSubtitle: "2시간 사냥 시급 · 누적 정산",
    calcResetAll: "전체 초기화",
    calcResetConfirm: "오늘의 모든 기록과 타이머를 초기화할까요?",
    calcMoreGuides: "최신 가이드 더보기 →",
    emptyGuides: "등록된 가이드가 없습니다.",
  },
  en: {
    brand: "Maple Meso Calculator",
    navAria: "Primary",
    secondaryAria: "Secondary",
    navCalculator: "Meso Calculator",
    navGuides: "Guides",
    navShowcase: "Showcase",
    navTips: "Tips",
    navFeedback: "Feedback",
    langSwitchLabel: "한국어",
    langSwitchAria: "한국어로 전환",
    footerLegalAria: "Legal",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Use",
    footerCopyright: (year: number, updated: string) =>
      `© ${year} wopsgame · Unofficial fan tool · Legal docs last updated: ${updated}`,
    guideIndexTitle: "Hunting & Meso Guides",
    guideIndexBlurb: "Tap a title to open the full guide. 10 guides per page.",
    guideBackHome: "← Back to Meso Calculator",
    guideBackList: "← All guides",
    guideListCta: "Back to guide list",
    viewsBest: "Most viewed",
    recommendsBest: "Most recommended",
    allGuides: "All guides",
    statsLoading: "Loading views & recommends…",
    statsCell: (rec: string, views: string) => `${rec} recommends · ${views} views`,
    prev: "Prev",
    next: "Next",
    relatedTitle: "Related guides",
    relatedAll: "All guides →",
    recommendDone: (n: string) => `Recommended · ${n}`,
    recommendCta: (n: string) => `Recommend · ${n}`,
    recommendAlready: "You already recommended this guide.",
    recommendThanks: "Thanks for the recommendation!",
    recommendFail: "Could not save recommendation. Please try again.",
    calcTitle: "Maple Meso Calculator",
    calcSubtitle: "2-hour hunt wage · running settlement",
    calcResetAll: "Reset all",
    calcResetConfirm: "Clear today’s records and timer?",
    calcMoreGuides: "Browse English guides →",
    emptyGuides: "No English guides yet. Check back soon.",
  },
} as const;

export function ui(locale: Locale) {
  return UI[locale];
}
